
export const translations = {
  hu: {
    // General
    next: "Tovább",
    back: "Vissza",
    clear_fields: "Mezők ürítése",
    upload: "Feltöltés",
    app_title: "Nehézgépjármű Áthaladási Engedély",
    footer_text: "Székelyudvarhely Megyei Jogú Város - 2025",
    data_correct_agreement: "Igazolom és kijelentem hogy az adatok helyesek!",

    // Step 1
    step1_title: "Igénylő adatai",
    applicant_type: "Igénylő típusa",
    natural_person: "Természetes személy",
    legal_entity: "Jogi személy",
    last_name: "Családnév",
    first_name: "Keresztnév",
    cnp: "Személyi szám (CNP)",
    email: "E-mail",
    phone: "Telefon",
    company_name: "Vállalat neve",
    tax_id: "Adószám",
    orc_number: "ORC szám",
    company_email: "Vállalati E-mail",
    company_phone: "Vállalati telefonszám",
    rep_last_name: "Képviselő családneve",
    rep_first_name: "Képviselő keresztneve",
    rep_status: "Képviselő státusza",
    rep_email: "Képviselő E-mail címe",
    rep_phone: "Képviselő telefonszáma",
    address_section: "Cím",
    street: "Utca",
    number: "Házszám",
    building: "Tömbház",
    staircase: "Lépcsőház",
    apartment: "Lakrész",
    city: "Város",
    county: "Megye",
    communication_agreement: "Beleegyezem, hogy az adataimat az intézmény felhasználja kommunikációra és értesítéseket küldjön nekem!",

    // Step 2
    step2_title: "Jármű és Útvonal Adatok",
    vehicle_data: "Jármű adatok",
    brand: "Márka",
    category: "Jármű kategória",
    license_plate: "Rendszám",
    max_weight: "Maximum tömeg (t)",
    vin: "Alvázszám",
    registration_document: "Forgalmi engedély",
    shipment_type_section: "Szállítmány típusa",
    shipment_type: "Szállítmány típusa",
    route_section: "Útvonal",
    route_description: "Útvonal leírása (érintett utcák)",
    zone: "Zóna",
    select_zone: "Válasszon zónát",
    zone_a: "A Zóna",
    zone_b: "B Zóna",
    city_map_button: "Város térkép",
    start_date: "Kezdő dátum",
    start_time: "Kezdő idő",
    period: "Időszak",
    select_period: "Válasszon időszakot",
    daily: "Napi",
    monthly: "Havi",
    semi_annually: "Félévi",
    annually: "Évi",
    permit_price: "Engedélyezési ár:",
    
    // Step 3
    step3_title: "Összesítés",
    summary_description: "Kérjük, ellenőrizze a megadott adatokat a folytatás előtt.",

    // Step 4
    step4_title: "Fizetés",
    payment_processing: "Fizetés feldolgozása...",
    payment_successful: "Sikeres fizetés!",
    payment_failed: "Sikertelen fizetés!",
    payment_failed_message: "A fizetés sikertelen volt. Kérjük, próbálja újra, vagy kezdje elölről a folyamatot.",
    start_over: "Kezdje elölről",
    simulate_success: "Sikeres fizetés szimulálása",
    simulate_failure: "Sikertelen fizetés szimulálása",

    // Step 5
    step5_title: "Befejezés",
    permit_generation_success: "Az engedély sikeresen legenerálva!",
    permit_info: "Az engedélyt PDF formátumban letöltheti. A dokumentumot elküldtük a megadott e-mail cím(ek)re is.",
    download_permit: "Engedély letöltése",
  },
  ro: {
    // General
    next: "Înainte",
    back: "Înapoi",
    clear_fields: "Golește câmpurile",
    upload: "Încarcă",
    app_title: "Autorizație de Tranzit pentru Vehicule Grele",
    footer_text: "Municipiul Odorheiu Secuiesc - 2025",
    data_correct_agreement: "Confirm și declar că datele sunt corecte!",

    // Step 1
    step1_title: "Datele solicitantului",
    applicant_type: "Tipul solicitantului",
    natural_person: "Persoană fizică",
    legal_entity: "Persoană juridică",
    last_name: "Nume de familie",
    first_name: "Prenume",
    cnp: "Cod Numeric Personal (CNP)",
    email: "E-mail",
    phone: "Telefon",
    company_name: "Numele companiei",
    tax_id: "Cod fiscal",
    orc_number: "Număr ORC",
    company_email: "E-mail companie",
    company_phone: "Telefon companie",
    rep_last_name: "Nume reprezentant",
    rep_first_name: "Prenume reprezentant",
    rep_status: "Statut reprezentant",
    rep_email: "E-mail reprezentant",
    rep_phone: "Telefon reprezentant",
    address_section: "Adresă",
    street: "Strada",
    number: "Număr",
    building: "Bloc",
    staircase: "Scara",
    apartment: "Apartament",
    city: "Oraș",
    county: "Județ",
    communication_agreement: "Sunt de acord ca datele mele să fie utilizate de către instituție pentru comunicare și pentru a-mi trimite notificări!",

    // Step 2
    step2_title: "Date Vehicul și Traseu",
    vehicle_data: "Date vehicul",
    brand: "Marcă",
    category: "Categoria vehiculului",
    license_plate: "Număr de înmatriculare",
    max_weight: "Masa maximă (t)",
    vin: "Serie de șasiu",
    registration_document: "Certificat de înmatriculare",
    shipment_type_section: "Tipul transportului",
    shipment_type: "Tipul transportului",
    route_section: "Traseu",
    route_description: "Descrierea traseului (străzi afectate)",
    zone: "Zonă",
    select_zone: "Selectați zona",
    zone_a: "Zona A",
    zone_b: "Zona B",
    city_map_button: "Harta orașului",
    start_date: "Data de începere",
    start_time: "Ora de începere",
    period: "Perioadă",
    select_period: "Selectați perioada",
    daily: "Zilnic",
    monthly: "Lunar",
    semi_annually: "Semestrial",
    annually: "Anual",
    permit_price: "Prețul autorizației:",

    // Step 3
    step3_title: "Sumar",
    summary_description: "Vă rugăm să verificați datele introduse înainte de a continua.",

    // Step 4
    step4_title: "Plată",
    payment_processing: "Procesare plată...",
    payment_successful: "Plată reușită!",
    payment_failed: "Plată eșuată!",
    payment_failed_message: "Plata a eșuat. Vă rugăm să încercați din nou sau să reluați procesul.",
    start_over: "Începeți din nou",
    simulate_success: "Simulează plată reușită",
    simulate_failure: "Simulează plată eșuată",

    // Step 5
    step5_title: "Finalizare",
    permit_generation_success: "Autorizația a fost generată cu succes!",
    permit_info: "Puteți descărca autorizația în format PDF. Documentul a fost trimis și la adresa(ele) de e-mail furnizată(e).",
    download_permit: "Descarcă autorizația",
  },
  en: {
    // General
    next: "Next",
    back: "Back",
    clear_fields: "Clear Fields",
    upload: "Upload",
    app_title: "Heavy Vehicle Transit Permit",
    footer_text: "Odorheiu Secuiesc Municipality - 2025",
    data_correct_agreement: "I confirm and declare that the data is correct!",
    
    // Step 1
    step1_title: "Applicant Information",
    applicant_type: "Applicant Type",
    natural_person: "Natural Person",
    legal_entity: "Legal Entity",
    last_name: "Last Name",
    first_name: "First Name",
    cnp: "Personal Identification Number (CNP)",
    email: "E-mail",
    phone: "Phone",
    company_name: "Company Name",
    tax_id: "Tax ID",
    orc_number: "ORC Number",
    company_email: "Company E-mail",
    company_phone: "Company Phone",
    rep_last_name: "Representative's Last Name",
    rep_first_name: "Representative's First Name",
    rep_status: "Representative's Status",
    rep_email: "Representative's E-mail",
    rep_phone: "Representative's Phone",
    address_section: "Address",
    street: "Street",
    number: "Number",
    building: "Building",
    staircase: "Staircase",
    apartment: "Apartment",
    city: "City",
    county: "County",
    communication_agreement: "I agree that my data may be used by the institution for communication and to send me notifications!",
    
    // Step 2
    step2_title: "Vehicle and Route Data",
    vehicle_data: "Vehicle Data",
    brand: "Brand",
    category: "Vehicle Category",
    license_plate: "License Plate",
    max_weight: "Maximum Weight (t)",
    vin: "VIN",
    registration_document: "Registration Certificate",
    shipment_type_section: "Shipment Type",
    shipment_type: "Shipment Type",
    route_section: "Route",
    route_description: "Route Description (affected streets)",
    zone: "Zone",
    select_zone: "Select Zone",
    zone_a: "Zone A",
    zone_b: "Zone B",
    city_map_button: "City Map",
    start_date: "Start Date",
    start_time: "Start Time",
    period: "Period",
    select_period: "Select Period",
    daily: "Daily",
    monthly: "Monthly",
    semi_annually: "Semi-annually",
    annually: "Annually",
    permit_price: "Permit Price:",
    
    // Step 3
    step3_title: "Summary",
    summary_description: "Please review the entered data before proceeding.",
    
    // Step 4
    step4_title: "Payment",
    payment_processing: "Processing payment...",
    payment_successful: "Payment Successful!",
    payment_failed: "Payment Failed!",
    payment_failed_message: "The payment has failed. Please try again or restart the process.",
    start_over: "Start Over",
    simulate_success: "Simulate Successful Payment",
    simulate_failure: "Simulate Failed Payment",

    // Step 5
    step5_title: "Completion",
    permit_generation_success: "Permit generated successfully!",
    permit_info: "You can download the permit in PDF format. The document has also been sent to the provided e-mail address(es).",
    download_permit: "Download Permit",
  },
  de: {
    // General
    next: "Weiter",
    back: "Zurück",
    clear_fields: "Felder leeren",
    upload: "Hochladen",
    app_title: "Durchfahrtsgenehmigung für schwere Fahrzeuge",
    footer_text: "Gemeinde Odorheiu Secuiesc - 2025",
    data_correct_agreement: "Ich bestätige und erkläre, dass die Daten korrekt sind!",

    // Step 1
    step1_title: "Angaben zum Antragsteller",
    applicant_type: "Antragstellertyp",
    natural_person: "Natürliche Person",
    legal_entity: "Juristische Person",
    last_name: "Nachname",
    first_name: "Vorname",
    cnp: "Persönliche Identifikationsnummer (CNP)",
    email: "E-Mail",
    phone: "Telefon",
    company_name: "Firmenname",
    tax_id: "Steuernummer",
    orc_number: "ORC-Nummer",
    company_email: "Firmen-E-Mail",
    company_phone: "Firmentelefon",
    rep_last_name: "Nachname des Vertreters",
    rep_first_name: "Vorname des Vertreters",
    rep_status: "Status des Vertreters",
    rep_email: "E-Mail des Vertreters",
    rep_phone: "Telefon des Vertreters",
    address_section: "Adresse",
    street: "Straße",
    number: "Hausnummer",
    building: "Gebäude",
    staircase: "Treppenhaus",
    apartment: "Wohnung",
    city: "Stadt",
    county: "Kreis",
    communication_agreement: "Ich stimme zu, dass meine Daten von der Institution zur Kommunikation und zum Senden von Benachrichtigungen verwendet werden dürfen!",
    
    // Step 2
    step2_title: "Fahrzeug- und Routendaten",
    vehicle_data: "Fahrzeugdaten",
    brand: "Marke",
    category: "Fahrzeugkategorie",
    license_plate: "Kennzeichen",
    max_weight: "Maximalgewicht (t)",
    vin: "Fahrgestellnummer",
    registration_document: "Zulassungsbescheinigung",
    shipment_type_section: "Transportart",
    shipment_type: "Transportart",
    route_section: "Route",
    route_description: "Routenbeschreibung (betroffene Straßen)",
    zone: "Zone",
    select_zone: "Zone auswählen",
    zone_a: "Zone A",
    zone_b: "Zone B",
    city_map_button: "Stadtplan",
    start_date: "Startdatum",
    start_time: "Startzeit",
    period: "Zeitraum",
    select_period: "Zeitraum auswählen",
    daily: "Täglich",
    monthly: "Monatlich",
    semi_annually: "Halbjährlich",
    annually: "Jährlich",
    permit_price: "Genehmigungspreis:",

    // Step 3
    step3_title: "Zusammenfassung",
    summary_description: "Bitte überprüfen Sie die eingegebenen Daten, bevor Sie fortfahren.",

    // Step 4
    step4_title: "Zahlung",
    payment_processing: "Zahlung wird bearbeitet...",
    payment_successful: "Zahlung erfolgreich!",
    payment_failed: "Zahlung fehlgeschlagen!",
    payment_failed_message: "Die Zahlung ist fehlgeschlagen. Bitte versuchen Sie es erneut oder starten Sie den Vorgang neu.",
    start_over: "Neu anfangen",
    simulate_success: "Erfolgreiche Zahlung simulieren",
    simulate_failure: "Fehlgeschlagene Zahlung simulieren",

    // Step 5
    step5_title: "Abschluss",
    permit_generation_success: "Genehmigung erfolgreich erstellt!",
    permit_info: "Sie können die Genehmigung im PDF-Format herunterladen. Das Dokument wurde auch an die angegebene(n) E-Mail-Adresse(n) gesendet.",
    download_permit: "Genehmigung herunterladen",
  },
};
